name: task_manager_app
description: "Task manager project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.2.2
  http: ^1.6.0
  logger: ^2.7.0
  email_validator: ^3.0.0
  shared_preferences: ^2.5.5
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/

flutter:
  uses-material-design: true
  assets:
    - assets/images/


